// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALwBsc9XNs9O4JG1QIG494XUPXhCF1CnM',
    appId: '1:459475578720:web:3f709de262e64497843805',
    messagingSenderId: '459475578720',
    projectId: 'auto-watering-7c50f',
    authDomain: 'auto-watering-7c50f.firebaseapp.com',
    databaseURL: 'https://auto-watering-7c50f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auto-watering-7c50f.firebasestorage.app',
    measurementId: 'G-D47T7JPX3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTHeMUj245rb3_R8n2laOEKLhREITwPng',
    appId: '1:459475578720:android:b29fda1848231936843805',
    messagingSenderId: '459475578720',
    projectId: 'auto-watering-7c50f',
    databaseURL: 'https://auto-watering-7c50f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auto-watering-7c50f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGgTKxRPyv4iAAVFKhZn6Iz7xT_8mREv4',
    appId: '1:459475578720:ios:27f62435c2b40b52843805',
    messagingSenderId: '459475578720',
    projectId: 'auto-watering-7c50f',
    databaseURL: 'https://auto-watering-7c50f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auto-watering-7c50f.firebasestorage.app',
    iosBundleId: 'com.example.plantapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGgTKxRPyv4iAAVFKhZn6Iz7xT_8mREv4',
    appId: '1:459475578720:ios:27f62435c2b40b52843805',
    messagingSenderId: '459475578720',
    projectId: 'auto-watering-7c50f',
    databaseURL: 'https://auto-watering-7c50f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auto-watering-7c50f.firebasestorage.app',
    iosBundleId: 'com.example.plantapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYfL1SBdQXgyzcKTl0ll5P9gG1RRYO9TA',
    appId: '1:459475578720:web:18c8811b6b2b5ad1843805',
    messagingSenderId: '459475578720',
    projectId: 'auto-watering-7c50f',
    authDomain: 'auto-watering-7c50f.firebaseapp.com',
    databaseURL: 'https://auto-watering-7c50f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auto-watering-7c50f.firebasestorage.app',
    measurementId: 'G-ZRGZFMLEFD',
  );

}